/*
 * Copyright (c) Huawei Device Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ActionType {
  // Start up 启动相关
  public static readonly ACTION_IS_REQUEST_PERMISSION = 'ACTION_IS_REQUEST_PERMISSION';
  public static readonly ACTION_SEND_PERMISSION_STATE = 'ACTION_SEND_PERMISSION_STATE';

  // Setting 相关
  public static readonly ACTION_CHANGE_TIME_LAPSE = 'ACTION_CHANGE_TIME_LAPSE';
  public static readonly ACTION_ASSISTIVE_GRID_VIEW = 'ACTION_ASSISTIVE_GRID_VIEW';
  public static readonly ACTION_SMART_BACK_SELFIE = 'ACTION_SMART_BACK_SELFIE';
  public static readonly ACTION_IS_OPEN_FILTER = 'ACTION_IS_OPEN_FILTER';
  public static readonly ACTION_AIGC_ENHANCE = 'ACTION_AIGC_ENHANCE';
  public static readonly ACTION_FLOATING_SHUTTER_BUTTON = 'ACTION_FLOATING_SHUTTER_BUTTON';
  public static readonly ACTION_CLOSE_DIALOG = 'ACTION_CLOSE_DIALOG';
  public static readonly ACTION_RESTORE_DIALOG_CONFIRM = 'ACTION_RESTORE_DIALOG_CONFIRM';
  public static readonly ACTION_LOCATION_PERMISSION_TO_SETTING = 'ACTION_LOCATION_PERMISSION_TO_SETTING';
  public static readonly ACTION_REFRESH_LOCATION_TOGGLE_ITEM = 'ACTION_REFRESH_LOCATION_TOGGLE_ITEM';
  public static readonly ACTION_LOAD_PHOTO_BROWSER = 'ACTION_LOAD_PHOTO_BROWSER';
  public static readonly ACTION_CHECK_CURRENT_DIRECTION = 'ACTION_CHECK_CURRENT_DIRECTION';
  public static readonly ACTION_UPDATE_HDR_STATE = 'ACTION_UPDATE_HDR_STATE';
  public static readonly ACTION_LOCATION_GUIDED_AUTHORIZATION = 'ACTION_LOCATION_GUIDED_AUTHORIZATION';
  public static readonly ACTION_CHANGE_TIMED_SHOT = 'ACTION_CHANGE_TIMED_SHOT';

  // Capture
  public static readonly ACTION_NIGHT_CAPTURE_START = 'ACTION_NIGHT_CAPTURE_START';
  public static readonly ACTION_TIME_LAPSE_CAPTURE_START = 'ACTION_TIME_LAPSE_CAPTURE_START';
  public static readonly ACTION_RESET_EXPOSURE_TIME = 'ACTION_CLEAR_EXPOSURE_TIME';
  public static readonly ACTION_NIGHT_CAPTURE_END = 'ACTION_NIGHT_CAPTURE_END';
  public static readonly ACTION_DELAY_SEND_CAPTURE_END = 'ACTION_DELAY_SEND_CAPTURE_END';
  public static readonly ACTION_TIME_LAPSE_CAPTURE_END = 'ACTION_TIME_LAPSE_CAPTURE_EN';
  public static readonly ACTION_NIGHT_FRAME_SHUTTER = 'ACTION_NIGHT_FRAME_SHUTTER';
  public static readonly ACTION_CONFIRM_CAPTURE_EFFECT = 'ACTION_CONFIRM_CAPTURE_EFFECT';
  public static readonly ACTION_SAVE_PICKER_FILE = 'ACTION_SAVE_PICKER_FILE';
  // 拍照动效（闪黑、快门声）
  public static readonly ACTION_CAPTURE_EFFECT = 'ACTION_CAPTURE_EFFECT';
  public static readonly ACTION_FRAME_SHUTTER_END = 'ACTION_FRAME_SHUTTER_END';
  public static readonly ACTION_NORMAL_FRAME_SHUTTER = 'ACTION_NORMAL_FRAME_SHUTTER';
  // 普通拍照模式长曝光动效相关
  public static readonly ACTION_LONG_EXPOSURE_SHUTTER = 'ACTION_LONG_EXPOSURE_SHUTTER';
  public static readonly ACTION_LONG_EXPOSURE_SHUTTER_END = 'ACTION_LONG_EXPOSURE_SHUTTER_END';
  // 普通拍照模式长曝光倒计时动效相关
  public static readonly ACTION_COUNT_DOWN_SHUTTER = 'ACTION_COUNT_DOWN_SHUTTER';
  public static readonly ACTION_COUNT_DOWN_SHUTTER_END = 'ACTION_COUNT_DOWN_SHUTTER_END';
  public static readonly ACTION_COUNT_DOWN_SHUTTER_AFTER_TIMELAPSE = 'ACTION_COUNT_DOWN_SHUTTER_AFTER_TIMELAPSE';
  public static readonly ACTION_HIDE_BUTTON = 'ACTION_HIDE_BUTTON';
  public static readonly ACTION_COUNT_DOWN_SHUTTER_AFTER_TIMED_SHOT = 'ACTION_COUNT_DOWN_SHUTTER_AFTER_TIMED_SHOT';

  // 底层实时预估的拍照速度
  public static readonly ACTION_ESTIMATED_CAPTURE_DURATION = 'ACTION_ESTIMATED_CAPTURE_DURATION';
  public static readonly ACTION_TIME_LAPSE_FRAME_SHUTTER = 'ACTION_TIME_LAPSE_FRAME_SHUTTER';

  // Record
  public static readonly ACTION_RECORD_START_SECONDS = 'ACTION_RECORD_START_SECONDS';
  public static readonly ACTION_RECORD_USELESS_SECONDS = 'ACTION_RECORD_USELESS_SECONDS';
  public static readonly ACTION_RECORD_PAUSE_TIME = 'ACTION_RECORD_PAUSE_TIME';
  public static readonly ACTION_UI_STATE = 'ACTION_UI_STATE';

  /********** NEW UI REMAKE START **********/
  // Camera
  public static readonly ACTION_DIRECTION_CHANGE = 'ACTION_DIRECTION_CHANGE';
  public static readonly ACTION_MOTION_DIRECTION_CHANGE = 'ACTION_MOTION_DIRECTION_CHANGE';
  public static readonly ACTION_INSTANT_DIRECTION_CHANGE = 'ACTION_INSTANT_DIRECTION_CHANGE';
  public static readonly ACTION_LOCK_ROTATION_CHANGE = 'ACTION_LOCK_ROTATION_CHANGE';

  // Mode
  public static readonly ACTION_SWIPE_CHANGE_MODE = 'ACTION_SWIPE_CHANGE_MODE';
  public static readonly ACTION_UPDATE_MODE_BAR = 'ACTION_UPDATE_MODE_BAR';
  public static readonly ACTION_UPDATE_MODE_POS = 'ACTION_UPDATE_MODE_POS';
  public static readonly ACTION_SHOW_MORE_PAGE = 'ACTION_SHOW_MORE_PAGE';
  public static readonly ACTION_EDIT_MORE_PAGE = 'ACTION_EDIT_MORE_PAGE';
  public static readonly CHANGE_MODE_PLAY_SOUND = 'CHANGE_MODE_PLAY_SOUND';
  public static readonly MORE_MODE_SLIDER_DOUBLE_STREAM_MODE = 'MORE_MODE_SLIDER_DOUBLE_STREAM_MODE';
  public static readonly DISABLE_MODE_BAR_CHANGED = 'DISABLE_MODE_BAR_CHANGED';
  public static readonly ACTION_THIRD_PARTY_CALL = 'ACTION_THIRD_PARTY_CALL';

  // 闪光灯
  public static readonly ACTION_FLASH_CHANGED = 'ACTION_FLASH_CHANGED';
  public static readonly ACTION_MORE_MODE_TAB_EMIT_FLASH = 'ACTION_MORE_MODE_TAB_EMIT_FLASH';

  // Preview
  public static readonly ACTION_CHANGE_X_COMPONENT_SIZE = 'ACTION_CHANGE_X_COMPONENT_SIZE';
  public static readonly ACTION_PREVIEW_CLICKED = 'ACTION_PREVIEW_CLICKED';
  public static readonly ACTION_PREVIEW_SHOT_COMPONENT = 'ACTION_PREVIEW_SHOT_COMPONENT';
  public static readonly ACTION_ON_BACK_PRESS = 'ACTION_ON_BACK_PRESS';

  // ONCE TOAST
  public static readonly ACTION_HANDLE_ONCE_TOAST = 'ACTION_HANDLE_ONCE_TOAST';

  //斜眼提示
  public static readonly ACTION_EYE_TIP_ANIM = 'ACTION_EYE_TIP_ANIM';

  // Record
  public static readonly ACTION_PICKER_REMAKE = 'ACTION_PICKER_REMAKE';
  public static readonly ACTION_SHOW_PICKER = 'ACTION_SHOW_PICKER';
  public static readonly ACTION_LIGHT_STATUS_CHANGE = 'ACTION_LIGHT_STATUS_CHANGE';
  // Ui
  public static readonly ACTION_UPDATE_SHOW_BIG_TEXT_FLAG = 'ACTION_UPDATE_SHOW_BIG_TEXT_FLAG';
  public static readonly ACTION_UPDATE_SHOW_NIGHT_BIG_TEXT_FLAG = 'ACTION_UPDATE_SHOW_NIGHT_BIG_TEXT_FLAG';
  public static readonly ACTION_UPDATE_SHOW_BURST_CAPTURE_BIG_TEXT_FLAG =
    'ACTION_UPDATE_SHOW_BURST_CAPTURE_BIG_TEXT_FLAG';
  public static readonly ACTION_UPDATE_SHUTTER_ICON = 'ACTION_UPDATE_SHUTTER_ICON';
  public static readonly ACTION_UPDATE_LIGHT_PAINTING_TIMER_STATE = 'ACTION_UPDATE_LIGHT_PAINTING_TIMER_STATE';
  public static readonly ACTION_UPDATE_LIGHT_PAINTING_EXTEND_BAR = 'ACTION_UPDATE_LIGHT_PAINTING_EXTEND_BAR';
  public static readonly ACTION_LIGHT_PAINTING_FLASH = 'ACTION_LIGHT_PAINTING_FLASH';
  public static readonly ACTION_NIGHT_SUB_REFRESH_TREASURE = 'ACTION_NIGHT_SUB_REFRESH_TREASURE';
  public static readonly ACTION_LIGHT_PAINTING_START_SECONDS = 'ACTION_LIGHT_PAINTING_START_SECONDS';
  public static readonly ACTION_LIGHT_PAINTING_TIMER = 'ACTION_LIGHT_PAINTING_TIMER';
  public static readonly ACTION_LIGHT_PAINTING_FLASH_TIMER_SHOW = 'ACTION_LIGHT_PAINTING_FLASH_TIMER_SHOW';
  public static readonly ACTION_LIGHT_PAINTING_TIMER_SHOW = 'ACTION_LIGHT_PAINTING_TIMER_SHOW';
  public static readonly ACTION_LIGHT_PAINTING_SET_FLASH_TIMER = 'ACTION_LIGHT_PAINTING_SET_FLASH_TIMER';
  public static readonly ACTION_LIGHT_PAINTING_SEND_FLASH_SWITCH = 'ACTION_LIGHT_PAINTING_SEND_FLASH_SWITCH';
  public static readonly ACTION_LIGHT_PAINTING_SET_TREASURE_BOX_LOTTIE = 'ACTION_LIGHT_PAINTING_SET_TREASURE_BOX_LOTTIE';
  public static readonly ACTION_SHOW_LIGHT_PAINTING_DIALOG = 'ACTION_SHOW_LIGHT_PAINTING_DIALOG';
  public static readonly ACTION_NIGHT_STAR_PORTRAIT_FLASH = 'ACTION_NIGHT_STAR_PORTRAIT_FLASH';

  public static readonly ACTION_IS_SHOW_FOOT_BAR = 'ACTION_IS_SHOW_FOOT_BAR';
  public static readonly ACTION_IS_SHOW_MODE_BAR = 'ACTION_IS_SHOW_MODE_BAR';
  public static readonly ACTION_IS_SHOW_PARAM_BAR = 'ACTION_IS_SHOW_PARAM_BAR';
  public static readonly ACTION_IS_SHOW_EXTEND_BAR = 'ACTION_IS_SHOW_EXTEND_BAR';
  public static readonly ACTION_IS_EXTEND_BAR_CONTINUATION = 'ACTION_IS_EXTEND_BAR_CONTINUATION';
  public static readonly ACTION_UPDATE_PORTRAIT_SLIDER = 'ACTION_UPDATE_PORTRAIT_SLIDER';
  public static readonly ACTION_IS_SHOW_ISO_VIEW = 'ACTION_IS_SHOW_ISO_VIEW';
  public static readonly ACTION_IS_SHOW_SHUTTER_VIEW = 'ACTION_IS_SHOW_SHUTTER_VIEW';
  public static readonly ACTION_UPDATE_FACE_DETECTION_VIEW = 'ACTION_UPDATE_FACE_DETECTION_VIEW';
  public static readonly ACTION_UPDATE_FOCUS_TRACKING_INFO = 'ACTION_UPDATE_FOCUS_TRACKING_INFO';
  public static readonly ACTION_UPDATE_SMART_BACK_SELFIE_FACE_DATA = 'ACTION_UPDATE_SMART_BACK_SELFIE_FACE_DATA';
  public static readonly ACTION_UPDATE_EYE_FOCUS_VIEW = 'ACTION_UPDATE_EYE_FOCUS_VIEW';
  public static readonly ACTION_IS_ENTER_IMMERSIVE = 'ACTION_IS_ENTER_IMMERSIVE';
  public static readonly ACTION_IS_SHOW_WATERMARK_PAGE = 'ACTION_IS_SHOW_WATERMARK_PAGE';
  public static readonly ACTION_IS_SHOW_WATERMARK_PARAM_PAGE = 'ACTION_IS_SHOW_WATERMARK_PARAM_PAGE';
  public static readonly ACTION_CHANGE_SHOW_EXTEND_COMPONENT = 'ACTION_CHANGE_SHOW_EXTEND_COMPONENT';
  public static readonly ACTION_ON_PREVIEW_FRAME_START = 'ACTION_ON_PREVIEW_FRAME_START';
  public static readonly ACTION_ON_COLLABORATE_PREVIEW_FRAME_START = 'ACTION_ON_COLLABORATE_PREVIEW_FRAME_START';
  public static readonly ACTION_HANDLE_ZOOM_VIBRATOR = 'ACTION_HANDLE_VIBRATOR';
  public static readonly ACTION_STOP_ZOOM_VIBRATOR = 'ACTION_STOP_VIBRATOR';
  public static readonly AUDIO_CONTROL_SHUTTER_BUTTON = 'AUDIO_CONTROL_SHUTTER_BUTTON';
  public static readonly ACTION_IS_SHOW_TREASURE_BOX = 'ACTION_IS_SHOW_TREASURE_BOX';
  public static readonly ACTION_IS_HIDE_TREASURE_BOX = 'ACTION_IS_HIDE_TREASURE_BOX';
  public static readonly ACTION_CLEAR_PAGE_OR_DIALOG = 'ACTION_CLEAR_PAGE_OR_DIALOG';
  public static readonly ACTION_LOG_MODE_CHANGE = 'ACTION_LOG_MODE_CHANGE'; // 罗汉果、延时摄影相关ui状态事件
  public static readonly ACTION_UPDATE_EXTEND_BAR_POSITION = 'ACTION_UPDATE_EXTEND_BAR_POSITION';

  public static readonly ACTION_IS_POSITION = 'ACTION_IS_POSITION';
  //collaboration remote onNewWant
  public static readonly ACTION_UPDATE_COLLABORATION_PHOTO_INFO = 'ACTION_UPDATE_COLLABORATION_PHOTO_INFO';
  // 锁屏相机相关
  public static readonly ACTION_IS_SECURITY_CAMERA = 'ACTION_IS_SECURITY_CAMERA';
  public static readonly ACTION_CAMERA_SHOT_KEY = 'ACTION_CAMERA_SHOT_KEY';
  public static readonly ACTION_CLOSE_SETTING_DIALOG = 'ACTION_CLOSE_SETTING_DIALOG';
  public static readonly ACTION_THUMBNAIL_REMINDER_SHOW = 'ACTION_THUMBNAIL_REMINDER_SHOW';
  public static readonly ACTION_APP_LOCK_REMINDER_SHOW = 'ACTION_APP_LOCK_REMINDER_SHOW';
  public static readonly ACTION_ON_SKETCH_STATUS_CHANGED = 'ACTION_ON_SKETCH_STATUS_CHANGED';
  public static readonly ACTION_ON_ISO_STATUS_CHANGED = 'ACTION_ON_SKETCH_STATUS_CHANGED';
  public static readonly ACTION_ON_APETURE_STATUS_CHANGED = 'ACTION_ON_APETURE_STATUS_CHANGED';
  public static readonly ACTION_ON_APERTURE_EFFECT_CHANGE = 'ACTION_ON_APERTURE_EFFECT_CHANGE';
  public static readonly ACTION_ON_LUMINATION_STATUS_CHANGED = 'ACTION_ON_LUMINATION_STATUS_CHANGED';
  public static readonly ACTION_ON_PROFESSION_SHUTTER_STATUS_CHANGED = 'ACTION_ON_PROFESSION_SHUTTER_STATUS_CHANGED';
  public static readonly ACTION_ON_PROFESSION_ABILITY_STATUS_CHANGED = 'ACTION_ON_PROFESSION_ABILITY_STATUS_CHANGED';
  public static readonly ACTION_ADD_PIP_SURFACE_ID = 'ACTION_ADD_PIP_SURFACE_ID';
  // 大图组件相关
  public static readonly ACTION_PHOTO_BROWSER_ON_BACK_PRESS = 'ACTION_PHOTO_BROWSER_ON_BACK_PRESS';
  //延时摄影
  public static readonly TIME_LAPSE_ACTION_RATE_SLIDER = 'TIME_LAPSE_ACTION_RATE_SLIDER';
  public static readonly ACTION_UI_CHECKED_ICON = 'ACTION_UI_CHECKED_ICON';
  public static readonly ACTION_LAPSE_AUTO = 'ACTION_LAPSE_AUTO';
  public static readonly ACTION_TIME_LAPSE_OPEN = 'ACTION_TIME_LAPSE_OPEN';
  public static readonly ACTION_LAPSE_INTERVAL = 'ACTION_LAPSE_INTERVAL';
  public static readonly ACTION_LAPSE_INTERVAL_TYPE = 'ACTION_LAPSE_INTERVAL_TYPE';
  public static readonly ACTION_LAPSE_KEEP_TIME = 'ACTION_LAPSE_KEEP_TIME';
  public static readonly ACTION_LAPSE_INTERVAL_RANGE = 'ACTION_LAPSE_INTERVAL_RANGE';
  public static readonly ACTION_UPDATE_TIME_LAPSE_SLIDER = 'ACTION_TIME_LAPSE_SLIDER';
  public static readonly ACTION_GET_TIME_LAPSE_INTERVAL_RANGE = 'ACTION_GET_TIME_LAPSE_INTERVAL_RANGE';
  public static readonly ACTION_GET_TIME_LAPSE_PAN_GESTURE_END = 'ACTION_GET_TIME_LAPSE_PAN_GESTURE_END';
  public static readonly ACTION_TIME_LAPSE_TRY_AE_DONE = 'ACTION_TIME_LAPSE_TRY_AE_DONE';
  public static readonly ACTION_TIME_LAPSE_RECORDING_STOP = 'ACTION_TIME_LAPSE_RECORDING_STOP';
  public static readonly ACTION_BUFFER_RECEIVED_TIMELAPSE = 'ACTION_BUFFER_RECEIVED_TIMELAPSE';
  public static readonly CHANGE_TIMELAPSE_VIDEO_STATE = 'CHANGE_TIMELAPSE_VIDEO_STATE';
  public static readonly ACTION_CLICK_AUTO_FOCUS = 'ACTION_CLICK_AUTO_FOCUS';
  //专业模式
  public static readonly ACTION_LUMATION_CHANGE_STATE = 'ACTION_LUMATION_CHANGE_STATE';
  public static readonly ACTION_PROSON_CHANGE_STATE = 'ACTION_PROSON_CHANGE_STATE';
  public static readonly ACTION_PROSON_CHANGE_VIEW = 'ACTION_PROSON_CHANGE_VIEW';
  public static readonly ACTION_UPDATE_ISO_RANGE = 'ACTION_UPDATE_ISO_RANGE';
  public static readonly ACTION_UPDATE_SUPER_ISO_VALUE = 'ACTION_UPDATE_SUPER_ISO_VALUE';
  public static readonly ACTION_UPDATE_ISO_VALUE = 'ACTION_UPDATE_ISO_VALUE';
  public static readonly ACTION_UPDATE_PHOTO_FORMAT = 'ACTION_UPDATE_PHOTO_FORMAT';
  public static readonly ACTION_CHANGE_PRO_FOCUS_MODE = 'ACTION_CHANGE_PRO_FOCUS_MODE';
  public static readonly ACTION_UPDATE_PRO_PARAMETERS_VALUE = 'ACTION_UPDATE_PRO_PARAMETERS_VALUE';

  //夜景模式
  public static readonly ACTION_UPDATE_NIGHT_EXTEND_BAR = 'ACTION_UPDATE_NIGHT_EXTEND_BAR';
  public static readonly UPDATE_IMAGE_STABILIZATION_GUIDE = 'UPDATE_IMAGE_STABILIZATION_GUIDE';
  public static readonly UPDATE_IMAGE_STABILIZATION_SHOW = 'UPDATE_IMAGE_STABILIZATION_SHOW';

  public static readonly ACTION_CHANGE_RESOLUTION = 'ACTION_CHANGE_RESOLUTION';

  // 分辨率
  public static readonly ACTION_UPDATE_ASPECT_RATIO = 'ACTION_UPDATE_ASPECT_RATIO';
  public static readonly ACTION_UPDATE_VIDEO_RESOLUTION = 'ACTION_UPDATE_VIDEO_RESOLUTION';
  public static readonly ACTION_PICKER_DPI_CHANGE = 'ACTION_PICKER_DPI_CHANGE';
  public static readonly ACTION_IS_UPDATE_ASPECT_RATIO = 'ACTION_IS_UPDATE_ASPECT_RATIO';

  //温控
  public static readonly ACTION_SHOW_EXIT_FLASH_DIALOG = 'ACTION_SHOW_EXIT_FLASH_DIALOG';
  public static readonly ACTION_SHOW_EXIT_CAMERA_DIALOG = 'ACTION_SHOW_EXIT_CAMERA_DIALOG';

  // 全景
  public static readonly ACTION_IS_PANORAMA_BTN_STATUS = 'ACTION_IS_PANORAMA_BTN_STATUS';
  public static readonly ACTION_IS_START_PANORAMA = 'ACTION_IS_START_PANORAMA';
  public static readonly ACTION_IS_START_PANORAMA_SHUTTER_BUTTON = 'ACTION_IS_START_PANORAMA_SHUTTER_BUTTON';
  public static readonly ACTION_IS_END_PANORAMA = 'ACTION_IS_END_PANORAMA';
  public static readonly ACTION_IS_TOAST_PANORAMA = 'ACTION_IS_TOAST_PANORAMA';
  public static readonly ACTION_TOAST_TEXT_INFO_PANORAMA = 'ACTION_TOAST_TEXT_INFO_PANORAMA';
  public static readonly ACTION_ON_PHOTO_STOP_PANORAMA = 'ACTION_ON_PHOTO_STOP_PANORAMA';
  public static readonly ACTION_ON_BACK_PRESS_STOP_PANORAMA = 'ACTION_ON_BACK_PRESS_STOP_PANORAMA';
  public static readonly PANORAMA_PROGRESS_RESULT = 'PANORAMA_PROGRESS_RESULT';
  public static readonly PANORAMA_RESULT = 'PANORAMA_RESULT';

  // 百香果-全景二代
  public static readonly ACTION_START_STITCHING_CAPTURE = 'ACTION_START_STITCHING_CAPTURE';
  public static readonly ACTION_END_STITCHING_CAPTURE = 'ACTION_END_STITCHING_CAPTURE';
  public static readonly ACTION_FINISH_STITCHING_CAPTURE = 'ACTION_FINISH_STITCHING_CAPTURE';
  public static readonly ACTION_UPDATE_TARGET_POSITION = 'ACTION_UPDATE_TARGET_POSITION';
  public static readonly ACTION_UPDATE_BASE_ANGLE = 'ACTION_UPDATE_BASE_ANGLE';
  public static readonly ACTION_UPDATE_STITCHING_PREVIEW = 'ACTION_UPDATE_STITCHING_PREVIEW';
  public static readonly ACTION_SHOW_STITCHING_HINT = 'ACTION_SHOW_STITCHING_HINT';
  public static readonly ACTION_ON_BACK_PRESS_STOP_STITCHING = 'ACTION_ON_BACK_PRESS_STOP_STITCHING';
  public static readonly ACTION_ON_STITCHING_RESTORE = 'ACTION_ON_STITCHING_RESTORE';

  public static readonly ACTION_IS_START_STITCHING_SHUTTER_BUTTON = 'ACTION_IS_START_STITCHING_SHUTTER_BUTTON';

  //低电量
  public static readonly ACTION_LOW_BATTERY_SHOW_EXIT_FLASH_DIALOG = 'ACTION_LOW_BATTERY_SHOW_EXIT_FLASH_DIALOG';

  public static readonly ACTION_UPDATE_FACE_SMILE_DETECTION = 'ACTION_UPDATE_FACE_SMILE_DETECTION';

  // 拍照权限公共弹窗
  public static readonly ACTION_COMMON_CAPTURE_PERMISSION_DIALOG = 'ACTION_COMMON_CAPTURE_PERMISSION_DIALOG';

  public static readonly ACTION_SWITCH_CAMERA_CHANGE_MODE_ONLY: string = 'ACTION_SWITCH_CAMERA_CHANGE_MODE_ONLY';

  public static readonly ACTION_UPDATE_GLOBAL_EXPOSURE_VALUE = 'ACTION_UPDATE_GLOBAL_EXPOSURE_VALUE';

  // 智拍键设置状态更新
  public static readonly ACTION_UPDATE_SMART_CONTROL_SWITCH_STATE = 'ACTION_UPDATE_SMART_CONTROL_SWITCH_STATE';

  // 智感设备翻转状态
  public static readonly ACTION_PHONE_FLIP = 'ACTION_PHONE_FLIP';

  // 电源键相关Action
  public static readonly ACTION_POWER_KEY_DURATION_ONE_SECOND = 'ACTION_POWER_KEY_DURATION_ONE_SECOND';

  // 画中画显示状态
  public static readonly ACTION_SHOW_PIP_SURFACE_CHANGE = 'ACTION_SHOW_PIP_SURFACE_CHANGE';

  // 拍照模式是否支持组件提亮
  public static readonly ACTION_SUPPORT_HDR_BRIGHTNESS = 'ACTION_SUPPORT_HDR_BRIGHTNESS';

  //首次进相机点击引导页同意
  public static readonly ACTION_INTRO_CONFIRM = 'ACTION_INTRO_CONFIRM';

  // TV拍立得卡片拍照倒计时Action
  public static readonly ACTION_TV_COUNTDOWN = 'ACTION_TV_COUNTDOWN';
}