/*
 * Copyright (c) Huawei Device Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export namespace WorkerTask {
  export const ACTION_RECOVERY_WORKER_THREAD = 'ACTION_RECOVERY_WORKER_THREAD';

  export const ACTION_INIT = 'ACTION_INIT';

  export const ACTION_INIT_CAMERA_LIST = 'ACTION_INIT_CAMERA_LIST';

  export const ACTION_START_UP = 'ACTION_START_UP';

  export const ACTION_START_PREVIEW = 'ACTION_START_PREVIEW';

  export const ACTION_ADD_DEFERRED_SURFACE = 'ACTION_ADD_DEFERRED_SURFACE';

  export const ACTION_SWAP_DEFERRED_SURFACE = 'ACTION_SWAP_DEFERRED_SURFACE';

  export const ACTION_CHANGE_MODE = 'ACTION_CHANGE_MODE';

  export const ACTION_SWITCH_CAMERA = 'ACTION_SWITCH_CAMERA';

  export const ACTION_SWITCH_CAMERA_CHANGE_MODE = 'ACTION_SWITCH_CAMERA_CHANGE_MODE';

  export const ACTION_RESTART_PREVIEW = 'ACTION_RESTART_PREVIEW';

  export const ACTION_SET_ZOOM_RATIO = 'ACTION_SET_ZOOM_RATIO';

  export const ACTION_CLOSE_CAMERA = 'ACTION_CLOSE_CAMERA';

  export const ACTION_STOP_PREVIEW_OUTPUT = 'ACTION_STOP_PREVIEW_OUTPUT';

  export const ACTION_CAPTURE = 'ACTION_CAPTURE';

  export const ACTION_ADD_PIP_SURFACE_ID = 'ACTION_ADD_PIP_SURFACE_ID';

  export const ACTION_RECORD_START = 'ACTION_RECORD_START';

  export const ACTION_RECORD_START_RECORDER = 'ACTION_RECORD_START_RECORDER';

  export const ACTION_RECORD_PAUSE = 'ACTION_RECORD_PAUSE';

  export const ACTION_RECORD_PAUSE_RECORDER = 'ACTION_RECORD_PAUSE_RECORDER';

  export const ACTION_RECORD_RESUME = 'ACTION_RECORD_RESUME';

  export const ACTION_RECORD_RESUME_RECORDER = 'ACTION_RECORD_RESUME_RECORDER';

  export const ACTION_RECORD_STOP = 'ACTION_RECORD_STOP';

  export const ACTION_RECORD_STOP_RECORDER = 'ACTION_RECORD_STOP_RECORDER';

  export const ACTION_SHUTTER_BUTTON_UP = 'ACTION_SHUTTER_BUTTON_UP';

  export const ACTION_NEED_DELETE_ONE_PIC = 'ACTION_NEED_DELETE_ONE_PIC';

  export const ACTION_START_BURST = 'ACTION_START_BURST';

  export const ACTION_STOP_BURST = 'ACTION_STOP_BURST';

  export const ACTION_UI_BURST_ONE = 'ACTION_UI_BURST_ONE';

  export const ACTION_CHANGE_FLASH_MODE = 'ACTION_CHANGE_FLASH_MODE';

  export const ACTION_CHANGE_STITCHING_TYPE = 'ACTION_CHANGE_STITCHING_TYPE';

  export const ACTION_CHANGE_STITCHING_DIRECTION = 'ACTION_CHANGE_STITCHING_DIRECTION';

  export const ACTION_CHANGE_STITCHING_MOVE = 'ACTION_CHANGE_STITCHING_MOVE';

  export const ACTION_SET_FOCUS = 'ACTION_SET_FOCUS';

  export const ON_SUPPORTED_NIGHT_SUB_MODE_TYPE = 'ACTION_SUPPORTED_NIGHT_SUB_MODE_TYPE';

  export const ON_NIGHT_IMAGE_STABILIZATION_GUIDE = 'ACTION_NIGHT_IMAGE_STABILIZATION_GUIDE';

  export const ACTION_IS_FOCUS_MODE_SUPPORTED = 'ACTION_IS_FOCUS_MODE_SUPPORTED';

  export const ACTION_SET_METERING_POINT = 'ACTION_SET_METERING_POINT';

  /**
   * 通知底层更新火龙果算法参数
   */
  export const ACTION_SET_CUSTOM_COLOR_STYLE_SETTING = 'ACTION_SET_CUSTOM_COLOR_STYLE_SETTING';

  export const ACTION_COLLABORATION_MODE = 'ACTION_COLLABORATION_MODE';

  export const ACTION_SET_XMAGE = 'ACTION_SET_XMAGE';

  export const ACTION_SET_VIDEO_STABILIZATION = 'ACTION_SET_VIDEO_STABILIZATION';

  export const ACTION_SET_PORTRAIT_EFFECT = 'ACTION_SET_PORTRAIT_EFFECT';

  export const ACTION_SET_PORTRAIT_BEAUTY = 'ACTION_SET_PORTRAIT_BEAUTY';

  export const ACTION_SET_PORTRAIT_BEAUTY_THEME = 'ACTION_SET_PORTRAIT_BEAUTY_THEME';

  export const ACTION_GET_LIGHT_PAINTING = 'ACTION_GET_LIGHT_PAINTING';

  export const ACTION_SET_LIGHT_PAINTING = 'ACTION_SET_LIGHT_PAINTING';

  export const ACTION_GET_AIGC_ENHANCE = 'ACTION_GET_AIGC_ENHANCE';

  export const ACTION_SET_AIGC_ENHANCE = 'ACTION_SET_AIGC_ENHANCE';

  export const ACTION_TRIGGER_LIGHTING = 'ACTION_TRIGGER_LIGHTING';

  export const ACTION_SET_EXPOSURE_VALUE = 'ACTION_SET_EXPOSURE_VALUE';

  export const ACTION_SET_EXPOSURE = 'ACTION_SET_EXPOSURE';

  export const ACTION_CONFIRM_CAPTURE = 'ACTION_CONFIRM_CAPTURE';

  export const ACTION_HANDLE_ZOOM_VIBRATOR = 'ACTION_HANDLE_VIBRATOR';

  export const ACTION_STOP_ZOOM_VIBRATOR = 'ACTION_STOP_VIBRATOR';

  export const ACTION_SET_EXPOSURE_MODE_BIAS = 'ACTION_SET_EXPOSURE_MODE_BIAS';

  export const ACTION_START_FACE_METADATA = 'ACTION_START_FACE_METADATA';

  export const ACTION_SET_NIGHT_SUB_MODE = 'ACTION_SET_NIGHT_SUB_MODE';

  export const ACTION_ENABLE_SUPER_MACRO = 'ACTION_ENABLE_SUPER_MACRO';

  export const ACTION_START_SESSION = 'ACTION_START_SESSION';

  export const ACTION_STOP_SESSION = 'ACTION_STOP_SESSION';

  export const ACTION_SAVE_PICKER_FILE = 'ACTION_SAVE_PICKER_FILE';

  export const ACTION_PREPARE_OR_UNPREPARE_ZOOM = 'ACTION_PREPARE_OR_UNPREPARE_ZOOM';

  export const ACTION_RECOVERY_RESTART_APP = 'ACTION_RECOVERY_RESTART_APP';

  export const ACTION_SET_SMOOTH_ZOOM = 'ACTION_SET_SMOOTH_ZOOM';

  export const ACTION_ENABLE_SCENE_FEATURE = 'ACTION_ENABLE_SCENE_FEATURE';

  export const ACTION_SET_VIRTUAL_APERTURE = 'ACTION_SET_VIRTUAL_APERTURE';

  export const ACTION_SET_PHYSICAL_APERTURE = 'ACTION_SET_PHYSICAL_APERTURE';

  export const ACTION_SET_SUPER_MOTION_DETECTION = 'ACTION_SET_SUPER_MOTION_DETECTION';

  export const ACTION_SET_WHITE_BALANCE = 'ACTION_SET_WHITE_BALANCE';

  export const ACTION_SET_APERTURE = 'ACTION_SET_APERTURE';

  export const ACTION_SET_ISO = 'ACTION_SET_ISO';

  export const ACTION_SET_METERING = 'ACTION_SET_METERING';

  export const ACTION_SET_AUXILIARY = 'ACTION_SET_AUXILIARY';

  export const ACTION_SET_LIVE_PHOTO = 'ACTION_SET_LIVE_PHOTO';

  export const ACTION_CAMERA_SHOT_KEY = 'ACTION_CAMERA_SHOT_KEY';

  export const ACTION_GET_FOCUS_DISTANCE = 'ACTION_GET_FOCUS_DISTANCE';

  export const ACTION_GET_ISO_RANGE = 'ACTION_GET_ISO_RANGE';

  export const ACTION_SET_IS_SHOW_LANDSCAPE = 'ACTION_SET_IS_SHOW_LANDSCAPE';

  export const ACTION_CONNECT_RENDER_AND_SEND = 'ACTION_CONNECT_RENDER_AND_SEND';

  export const ACTION_SEND_DIRECTION = 'ACTION_SEND_DIRECTION';

  export const ACTION_SET_EFFECT_SUGGESTION_STATUS = 'ACTION_SET_EFFECT_SUGGESTION_STATUS';

  export const ACTION_UPDATE_EFFECT_SUGGESTION = 'ACTION_UPDATE_EFFECT_SUGGESTION';

  export const ON_PHOTO_SAVED = 'photo';

  export const ON_PICKER_PHOTO_RECEIVED = 'picker_photo_received';

  export const ON_BUFFER_RECEIVED_TIMELAPSE = 'ON_BUFFER_RECEIVED_TIMELAPSE';

  export const ON_QUICK_THUMBNAIL = 'onQuickThumbnail';

  export const ON_CAPTURE_ID_QUICK_THUMBNAIL = 'ON_CAPTURE_ID_QUICK_THUMBNAIL';

  export const ON_CAPTURE_ID_PHOTO_ASSET = 'ON_CAPTURE_ID_PHOTO_ASSET';

  export const ON_THUMBNAIL_FILE_CREATED = 'ON_THUMBNAIL_FILE_CREATED';

  export const ON_NEXT_CAPTURE = 'onNextCapture';

  export const ON_VIDEO_URI = 'videoUri';

  export const ON_COLLABORATION_FD = 'collaborationFd';

  export const ON_FACE_METADATA_OBJECT = 'faceMetadataObject';

  export const ON_SMART_BACKSELFIE_FACE_METADATA_OBJECT = 'smartBackSelfieFaceMetadataObject';

  export const ON_RECORD_ERROR = 'recordError';

  export const ON_CAMERA_ERROR = 'cameraError';

  export const ON_CAMERA_STATUS = 'cameraStatus';

  export const ON_CAMERA_DESTROY_SESSION_TIMEOUT = 'ON_CAMERA_DESTROY_SESSION_TIMEOUT';

  export const PC_PICKER_RECEIVED = 'PC_PICKER_RECEIVED';

  export const ON_TIME_LAPSE_TRY_AE_DONE = 'ON_TIME_LAPSE_TRY_AE_DONE';

  export const ON_STARS_INFO_REPORT = 'ON_STAR_INFO_REPORT';

  export const ON_CLOSE_CAMERA_TIMEOUT = 'ON_CLOSE_CAMERA_TIMEOUT';

  export const ON_SAVE_PICTURE_FAILED = 'ON_SAVE_PICTURE_FAILED';

  export const ON_VIDEO_RECORDING_STATUS = 'ON_VIDEO_RECORDING_STATUS';

  export const ON_SAVE_VIDEO_FAIL = 'ON_SAVE_VIDEO_FAIL';

  export const ON_SKETCH_STATUS_CHANGED = 'ON_SKETCH_STATUS_CHANGED';

  export const ON_PREVIEW_FRAME_START = 'onPreviewFrameStart';

  export const ON_DEPTH_FUSION_ZOOM_THRESHOLD = 'onDepthFusionZoomThreshold';

  export const ON_COLLABORATE_PREVIEW_FRAME_START = 'onCollaboratePreviewFrameStart';

  export const ON_COLLABORATE_CONTROL_PREVIEW_FRAME_START = 'onCollaborateControlPreviewFrameStart';

  export const ON_COLLABORATE_CONTROL_PREVIEW_FRAME_END = 'onCollaborateControlPreviewFrameEnd';

  export const ON_COLLABORATE_CONTROL_PREVIEW_FRAME_ERROR = 'onCollaborateControlPreviewFrameError';

  export const ON_START_CAMERA_DURATION = 'onStartCameraDuration';

  export const ON_CAMERA_PROCESS_DURATION = 'onCameraProcessDuration';

  export const ON_START_CAMERA_POSITION_AND_MODE = 'onStartCameraPositionAndMode';

  export const ON_USER_BEHAVIOR_PHOTO_INTERVAL = 'ON_USER_BEHAVIOR_PHOTO_INTERVAL';

  export const ON_NIGHT_CAPTURE_START = 'captureStart';

  export const ON_NIGHT_CAPTURE_END = 'captureEnd';

  export const ON_NIGHT_FRAME_SHUTTER = 'nightFrameShutter';

  export const ON_CONSTELLATION_MATCHING_STATE = 'constellationMatchingState';

  export const ON_NORMAL_FRAME_SHUTTER = 'normalFrameShutter';

  export const ON_FIRST_BURST_AVAILABLE = 'onFirstBurstAvailable';

  export const ON_PHOTO_PROCESSED = 'photoProcessed';

  export const ON_BURST_PHOTO_TOOK = 'burstPhotoTook';

  export const ON_BURST_DATA_REPORT = 'burstDataReport';

  export const ON_BURST_FINISH_RESET = 'burstFinishReset';

  export const ON_DEFER_PHOTO_REPORT = 'onDeferPhotoReport';

  export const ON_DEFER_PHOTO_MEDIA_URI = 'onDeferPhotoMediaUri';

  export const ON_UPDATE_VALID_FRAME_FLAG = 'onUpdateValidFrameFlag';

  export const ON_SCENE_FEATURE_DETECTION_RESULT = 'ON_SCENE_FEATURE_DETECTION_RESULT';

  export const ON_CAPTURE_ABORTED = 'onCaptureAborted';

  export const ON_FRAME_SHUTTER_END = 'onFrameShutterEnd';

  export const ON_ESTIMATED_CAPTURE_DURATION = 'estimatedCaptureDuration';

  export const ON_UPDATE_EXPOSURE_RECOVERY_FLAG = 'onUpdateExposureRecoveryFlag';

  export const ON_UPDATE_ISO_DURATION = 'onUpdateIsoDuration';

  export const ON_UPDATE_PHYSICAL_APERTURE_DURATION = 'onUpdatePhysicalApertureDuration';

  export const ON_UPDATE_EXPOSURE_DURATION = 'onUpdateExposureDuration';

  export const ON_PROFESSION_ABILITY_CHANGE = 'onAbilityChange';

  export const ON_SUPER_MOTION_STATUS = 'onSuperMotionStateOn';

  export const ON_SLOW_MOTION_ZOOM_RANGE = 'onSlowMotionZoomRange';

  export const ON_SLOW_MOTION_PREVIEW_CHANGE = 'onSlowMotionPreviewChange';

  export const ON_FLASH_STATUS = 'onFlashStatus';

  export const ON_PREEMPTION = 'ON_PREEMPTION';

  export const ACTION_SET_TIME_LAPSE = 'ACTION_SET_TIME_LAPSE';

  export const ACTION_SET_TIME_LAPSE_INTERVAL = 'ACTION_SET_TIME_LAPSE_INTERVAL';

  export const ACTION_ENABLE_DEPTH_FUSION = 'ACTION_ENABLE_DEPTH_FUSION';

  export const ACTION_IS_DEPTH_FUSION_CONFIGURED = 'ACTION_IS_DEPTH_FUSION_CONFIGURED';

  export const ACTION_GET_TIME_LAPSE_INTERVAL = 'ACTION_GET_TIME_LAPSE_INTERVAL';

  export const ON_EFFECT_SUGGESTION_CHANGE = 'ON_EFFECT_SUGGESTION_CHANGE';

  export const ACTION_RESET_PRO_EFFECT = 'ACTION_CONFIRM_CAPTURE';

  export const ACTION_ON_LENS_BLOCKING = 'ACTION_ON_LENS_BLOCKING';

  export const ACTION_ON_LENS_DIRTY = 'ACTION_ON_LENS_DIRTY';

  export const ACTION_REFRESH_PICKER_INFO = 'ACTION_REFRESH_PICKER_INFO';

  export const ACTION_PANORAMA_MAX_START = 'ACTION_PANORAMA_MAX_START';

  export const ACTION_PANORAMA_MIN_START = 'ACTION_PANORAMA_MIN_START';

  export const ACTION_PANORAMA_MAX_STOP = 'ACTION_PANORAMA_MAX_STOP';

  export const ACTION_PANORAMA_MIN_STOP = 'ACTION_PANORAMA_MIN_STOP';

  export const SWITCH_COLLABORATION = 'SWITCH_COLLABORATION';

  export const ACTION_COLLABORATE_CONTROL_PREVIEW_OUTPUT = 'ACTION_COLLABORATE_CONTROL_PREVIEW_OUTPUT';

  export const CHANGE_LOCATION = 'CHANGE_LOCATION';

  export const OPEN_PRE_RECORD = 'OPEN_PRE_RECORD';

  export const SET_VIDEO_FILTER = 'SET_VIDEO_FILTER';

  export const SET_MIRROR = 'SET_MIRROR';

  export const AUTO_FRAME_RATE = 'AUTO_FRAME_RATE';

  export const REPORT_LOSE_PHOTO = 'REPORT_LOSE_PHOTO';

  export const OPEN_FAILED = 'OPEN_FAILED';

  export const BURST_START_FAILED = 'BURST_START_FAILED';

  export const EYE_FOCUS = 'EYE_FOCUS';

  export const SMILE_CAPTURE = 'SMILE_CAPTURE';

  export const SET_OPERATION_EMOTION = 'SET_OPERATION_EMOTION';

  export const SET_WIND_NOISE_SUPPRESSION = 'SET_WIND_NOISE_SUPPRESSION';

  export const SET_SWING_SUBSCRIBE_STATUS = 'SET_SWING_SUBSCRIBE_STATUS';

  export const ACTION_DELETE_PICKER_VIDEO_FILE = 'ACTION_DELETE_PICKER_VIDEO_FILE';

  export const RECEIVED_PRE_RECORD_DURATION_TIME = 'RECEIVED_PRE_RECORD_DURATION_TIME';

  export const ACTION_SUPER_PRIVACY_MODE_ENABLED = 'ACTION_SUPER_PRIVACY_MODE_ENABLED';

  export const ADD_PHOTO_COUNT = 'ADD_PHOTO_COUNT';

  export const MINUS_PHOTO_COUNT = 'MINUS_PHOTO_COUNT';

  export const ON_DEFER_PHOTO_SAVE_END = 'ON_DEFER_PHOTO_SAVE_END';

  export const RESET_PHOTO_COUNT = 'RESET_PHOTO_COUNT';

  export const SET_CAMERA_CLOSE_FLAG = 'SET_CLOSE_CAMERA_FLAG';

  export const RESET_WORKER_PHOTO_COUNT = 'RESET_WORKER_PHOTO_COUNT';

  export const SHOW_SNAPSHOT_END = 'ULTRA_SHOW_SNAPSHOT_END';

  export const ON_UPDATE_START_PREVIEW_TIME = 'ON_UPDATE_START_PREVIEW_TIME';

  export const SET_AUDIO_EXTRA = 'SET_AUDIO_EXTRA';

  export const SET_ADDSURFACE_TIME = 'SET_ADDSURFACE_TIME';
  
  export const ON_SCAN_CODE_DETECT_RESULT = 'ON_SCAN_CODE_DETECT_RESULT';

  export const ON_PICKER_RELEASE_FROM_MAIN = 'ON_PICKER_RELEASE_FROM_MAIN';

  export const SET_SHORT_VIDEO_INDEX = 'SET_SHORT_VIDEO_INDEX';

  export const KEEP_USING_STELLAR_LENSES = 'KEEP_USING_STELLAR_LENSES';

  export const SCAN_CODE_CLOSE = 'SCAN_CODE_CLOSE';

  export const ON_STITCHING_TARGET_METADATA = 'ON_STITCHING_TARGET_METADATA';

  export const ON_STITCHING_CAPTURE_STATUS = 'ON_STITCHING_CAPTURE_STATUS';

  export const ON_STITCHING_PREVIEW = 'ON_STITCHING_PREVIEW';

  export const ON_STITCHING_HINT = 'ON_STITCHING_HINT';

  export const ENABLE_AI_COMPOSITION = 'ENABLE_AI_COMPOSITION';

  export const ON_RECV_AI_COMPOSITION_BEGIN_NOTICE = 'ON_RECV_AI_COMPOSITION_BEGIN_NOTICE';

  export const ON_RECV_AI_COMPOSITION_CALIBRATION_DATA = 'ON_RECV_AI_COMPOSITION_CALIBRATION_DATA';

  export const ON_RECV_AI_COMPOSITION_CONFIG_DATA = 'ON_RECV_AI_COMPOSITION_CONFIG_DATA';

  export const ON_UPDATE_FOCUS_TRACKING_INFO = 'ON_UPDATE_FOCUS_TRACKING_INFO';

  export const ON_APERTURE_EFFECT_CHANGE = 'ON_APERTURE_EFFECT_CHANGE';

  export const ON_RECV_AI_COMPOSITION_END_DATA = 'ON_RECV_AI_COMPOSITION_END_DATA';

  export const ENABLE_LOG_ASSISTANCE = 'ENABLE_LOG_ASSISTANCE';

  export const ON_LIGHT_STATUS_CHANGE = 'ON_LIGHT_STATUS_CHANGE';

  export const CHANGE_COLLABORATION_PREVIEWOUTPUT = 'CHANGE_COLLABORATION_PREVIEWOUTPUT';

  export const ACTION_CHANGE_CONSTELLATION_STATUS = 'ACTION_CHANGE_CONSTELLATION_STATUS';

  export const ON_RECORD_PAUSED = 'ON_RECORD_PAUSED';
  
  export const UPDATE_FOCUS_STATE = 'UPDATE_FOCUS_STATE';

  export const ACTION_SET_FOCUS_TRACKING_MODE = 'ACTION_SET_FOCUS_TRACKING_MODE';

  export const RESET_VIDEO_FILE_MANAGER_URI = 'RESET_VIDEO_FILE_MANAGER_URI';

  export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';

  export const UPDATE_HDR_SUPPORT = 'UPDATE_HDR_SUPPORT';

  export const SET_ULTRA_PHOTO = 'SET_ULTRA_PHOTO';

  export const SAVE_MOVIE_INFO_ASSET_DONE = 'SAVE_MOVIE_INFO_ASSET_DONE';

  export const SET_PREVIEW_ROTATION = 'SET_PREVIEW_ROTATION';

  export const VIDEO_STATE_CHANGE = 'VIDEO_STATE_CHANGE';

  export const ON_VIDEO_FRAME_END = 'ON_VIDEO_FRAME_END';
}