/*
 * Copyright (c) Huawei Device Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum PropTag {
  MODE = 'MODE',
  CAMERA_POSITION = 'CAMERA_POSITION',
  TREASURE_BOX = 'TREASURE_BOX',
  FLOATING_SHUTTER = 'FLOATING_SHUTTER',
  IS_INTRO_LOADED = 'IS_INTRO_LOADED',
  WATERMARK_VIEW = 'WATERMARK_VIEW',
  WATERMARK_CUSTOM_FILTER_PARAM_STATUS = 'WATERMARK_CUSTOM_FILTER_PARAM_STATUS',
  IS_UPDATED_WATERMARK_STATUS = 'IS_UPDATED_WATERMARK_STATUS',
  LAST_HDR_VIVID = 'LAST_HDR_VIVID',
  FILTER_CONFLICT_RESOLUTION = 'FILTER_CONFLICT_RESOLUTION',
  OUTPUT_SWITCHER = 'OUTPUT_SWITCHER',
  // 各种提示缓存key
  SLOW_MO_FIRST_TOAST = 'SLOW_MO_FIRST_TOAST', // 超慢toast只提示一次
  PRO_EXPOSURE_FIRST_TOAST = 'PRO_EXPOSURE_FIRST_TOAST',
  AUDIO_ZOOM_THREE_TOAST = 'AUDIO_ZOOM_THREE_TOAST', // 音频变焦提示三次
  CUSTOM_FILTER_SWIPE_TOAST = 'CUSTOM_FILTER_SWIPE_TOAST', // 个性风格滑动提示三次
  NIGHT_SUBMODE_THREE_TOAST = 'NIGHT_SUBMODE_THREE_TOAST', // 新夜景模式最多提示三次
  //
  IS_REQUESTED_PERMISSION = 'IS_REQUESTED_PERMISSION', // 是否已经申请过地理位置权限授权弹窗
  IS_JUMP_TO_SETTING = 'IS_JUMP_TO_SETTING', // 是否点击前往设置地理位置权限
  MORE_PAGE_MODE = 'MORE_PAGE_MODE', // 更多页模式数据缓存
  CAMERA_MODE_LIST_DATA = 'CAMERA_MODE_LIST_DATA', // 全局模式缓存
  PROFESSION_MODE = 'PROFESSION_MODE',
  IS_TIME_LAPSE_DETAIL_CARD_LOADED = 'IS_TIME_LAPSE_DETAIL_CARD_LOADED',
  IS_SEMI_COLLAPSED_GUIDE_LOAD = 'IS_SEMI_COLLAPSED_GUIDE_LOAD',
  ENTER_ROUND_THUMBNAIL_COUNT = 'ENTER_ROUND_THUMBNAIL_COUNT', // 外屏相机进入缩略图次数
  IS_FLUOR_LOADED = 'IS_FLUOR_LOADED',
  IS_PORTRAIT_MODE_INTRO_DIALOG_LOADED = 'IS_PORTRAIT_MODE_INTRO_DIALOG_LOADED',
  IS_PRO_MODE_INTRO_DIALOG_LOADED = 'IS_PRO_MODE_INTRO_DIALOG_LOADED',
  IS_TIME_LAPSE_MODE_INTRO_DIALOG_LOADED = 'IS_TIME_LAPSE_MODE_INTRO_DIALOG_LOADED',
  IS_FLUOR_MODE_INTRO_DIALOG_LOADED = 'IS_FLUOR_MODE_INTRO_DIALOG_LOADED',
  IS_NIGHT_MODE_INTRO_DIALOG_LOADED = 'IS_NIGHT_MODE_INTRO_DIALOG_LOADED',
  IS_STITCHING_MODE_INTRO_DIALOG_LOADED = 'IS_STITCHING_MODE_INTRO_DIALOG_LOADED',
  IS_STAGE_MODE_INTRO_DIALOG_LOADED = 'IS_STITCHING_MODE_INTRO_DIALOG_LOADED',   //stage模式的介绍页是否被加载过
  PICKER_IS_BANNER_LOADED = 'PICKER_IS_BANNER_LOADED',
  BACK_SELFIE = 'BACK_SELFIE',
  INTRO_AGREE_TIME = 'INTRO_AGREE_TIME',
  APPLICATION_VERSION = 'APPLICATION_VERSION',
  VIDEO_STABILIZATION_RESOLUTION = 'VIDEO_STABILIZATION_RESOLUTION',
  IS_LIGHT_PAINTING_DIALOG_LOADED = 'IS_LIGHT_PAINTING_DIALOG_LOADED',
  IS_LIGHT_PAINTING_DIALOG_OPENED = 'IS_LIGHT_PAINTING_DIALOG_OPENED',
  IS_CLOSE_PORTRAIT_BEAUTY = 'IS_CLOSE_PORTRAIT_BEAUTY',
  PRIVACY_VERSION = 'PRIVACY_VERSION',
  LOW_ANGLE = 'LOW_ANGLE',
  CUSTOM_COLOR_STYLES = 'CUSTOM_COLOR_STYLES',
  CUSTOM_COLOR_STYLE_SELECTED_INDEX = 'CUSTOM_COLOR_STYLE_SELECTED_INDEX',
  CUSTOM_COLOR_STYLE_ENABLED = 'CUSTOM_COLOR_STYLE_ENABLED',
  FIRST_FOREGROUND_AFTER_RESTORE = 'FIRST_FOREGROUND_AFTER_RESTORE',
  IS_SHOW_CUSTOM_COLOR_STYLE_DIAL = 'IS_SHOW_CUSTOM_COLOR_STYLE_DIAL',
  AUDIO_ZOOM_TIMESTAMP = 'AUDIO_ZOOM_TIMESTAMP', //音频变焦上次弹出时间戳
  EFFECT_SUGGESTION_TIP = 'EFFECT_SUGGESTION_TIP',
  IS_RESTORE_DEFAULT_VALUE = 'IS_RESTORE_DEFAULT_VALUE',
  LAST_SHOW_TREASURE_BOX_TIP_TIMESTAMP = 'LAST_SHOW_TREASURE_BOX_TIMESTAMP', // 百宝箱设置上次提示弹出时间戳
  SHOW_TREASURE_BOX_TIP_COUNT = 'SHOW_TREASURE_BOX_TIP_COUNT', // 百宝箱设置提示弹出次数
  IS_FRONT_CAMERA_TIPS_LOADED = 'IS_FRONT_CAMERA_TIPS_LOADED',
  FIRST_START_AFTER_DOUBLE_TO_SINGLE_OTA = 'FIRST_START_AFTER_DOUBLE_TO_SINGLE_OTA',
  HAS_BAR_MODE_LIST_BEEN_EDITED = 'HAS_MODE_BAR_LIST_BEEN_EDITED',
  IS_AUTO_CLOSE_FLASH = 'IS_AUTO_CLOSE_FLASH', // 是否zoom到指定点自动关闭闪光灯
  IS_MIRROR_SELFIE_GUIDE_DIALOG_CLOSED = 'IS_MIRROR_SELFIE_GUIDE_DIALOG_CLOSED', // 魔镜外屏引导是否已关闭
  TOGGLE_AUTO_UE_REPORT_DATE = 'TOGGLE_AUTO_UE_REPORT_DATE',
  IS_PITCH_ANGLE_INTRO_LOADED = 'IS_PITCH_ANGLE_INTRO_LOADED',
  IS_ROTATION_SUGGESTION_INTRO_LOADED = 'IS_ROTATION_SUGGESTION_INTRO_LOADED',
  IS_LOG_ASSISTANCE_OPEN = 'IS_LOG_ASSISTANCE_OPEN', // LOG模式的辅助监看是否打开
  STITCHING_TYPE = 'STITCHING_TYPE', // 百香果画幅模式
  STITCHING_DIRECTION = 'STITCHING_DIRECTION', // 百香果拍摄方向
  STITCHING_MOVE = 'STITCHING_MOVE', // 百香果长画幅方向
  STITCHING_HINT_COUNT = 'STITCHING_HINT_COUNT', // 百香果提示语次数计数
  NIGHT_CONSTELLATION_SUPERSTAR = 'NIGHT_CONSTELLATION_SUPERSTAR', // 绚丽星空模式星座绘制开关状态
  NIGHT_CONSTELLATION_STARRYSKYPORTRAIT = 'NIGHT_CONSTELLATION_STARRYSKYPORTRAIT', // 星空人像模式星座绘制开关状态
  BUNDLE_STATS_TIMESTAMP = 'BUNDLE_STATS_TIMESTAMP', //存储内存上次上报时间戳
  BACKGROUND_CAMERA_TIMESTAMP = 'BACKGROUND_CAMERA_TIMESTAMP', // 退出相机时间戳
  IS_AI_COMPOSITION_FIRST_OPEN = 'IS_AI_COMPOSITION_FIRST_OPEN', // AI 辅助构图开关开启时引导toast是否已加载过
  IS_FIRST_TIME_SUGGESTED_POINT_COMPLETED = 'IS_FIRST_TIME_SUGGESTED_POINT_COMPLETED', // 是否首次完成 AI 构图推荐点流程
  IS_FIRST_TIME_PITCH_ANGLE_COMPLETED = 'IS_FIRST_TIME_PITCH_ANGLE_COMPLETED', // 是否首次完成 AI 构图俯仰角流程
  IS_FIRST_TIME_ROTATION_SUGGESTION_COMPLETED = 'IS_FIRST_TIME_ROTATION_SUGGESTION_COMPLETED', // 是否首次完成 AI 构图旋转推荐流程
  IS_CUSTOM_FILTER_CARD_PITCH_SHOWED = 'IS_CUSTOM_FILTER_CARD_PITCH_SHOWED', //首次使用火龙果时Lottie是否已经显示过
  IS_CUSTOM_FILTER_CARD_MORE_HINT_SHOWED = 'IS_CUSTOM_FILTER_CARD_MORE_HINT_SHOWED', //首次使用火龙果时更多提示语是否已经显示过
  IS_CUSTOM_FILTER_LOTTIE_POP_TIP_SHOWED = 'IS_CUSTOM_FILTER_LOTTIE_POP_TIP_SHOWED',//TABBAR里个性风格图标的提示是否显示过
  IS_CUSTOM_FILTER_CARD_PARAM_BAR_HINT_SHOWED = 'IS_CUSTOM_FILTER_CARD_PARAM_BAR_HINT_SHOWED', // 出现火龙果调色按钮提示语是否显示
}

export enum PublicTag {
  IS_INTRO_LOADED = 'IS_INTRO_LOADED',
  IS_GUIDANCE_LOADED = 'IS_GUIDANCE_LOADED',
  ULTRA_SNAPSHOT_SELECTOR = 'ULTRA_SNAPSHOT_SELECTOR', // 熄屏快拍场景
  IS_LOW_BATTERY_TIP_OPENED = 'IS_LOW_BATTERY_TIP_OPENED',
  FLASH_STATE = 'FLASH_STATE',
  AUXILIARY_STATE = 'AUXILIARY_STATE',
  LIGHT_PAINTING_FLASH_STATE = 'LIGHT_PAINTING_FLASH_STATE',
  IS_PORTRAIT_BEAUTY_DIALOG_LOADED = 'IS_PORTRAIT_BEAUTY_DIALOG_LOADED',
  IS_REQUEST_LOCATION_DIALOG_LOADED = 'IS_REQUEST_LOCATION_DIALOG_LOADED',
  IS_TREASURE_BOX_TIP_LOADED = 'IS_TREASURE_BOX_TIP_LOADED',
  PICKER_IS_BANNER_LOADED = 'PICKER_IS_BANNER_LOADED',
  SMART_CONTROL_SLIDE_SHOW = 'SMART_CONTROL_SLIDE_SHOW',
  SMART_CONTROL_LONG_TOUCH_SHOW = 'SMART_CONTROL_LONG_TOUCH_SHOW',
  SMART_CONTROL_LIGHT_TOUCH_SHOW = 'SMART_CONTROL_LIGHT_TOUCH_SHOW'
}

export enum FunctionFirstToast { //各种特性首次提示状态
  NONE_TOAST = 'NONE_TOAST',
  SHOW_TOAST = 'SHOW_TOAST',
  HIDE_TOAST = 'HIDE_TOAST'
}